version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: unset JAVA_TOOL_OPTIONS && unset GRADLE_OPTS && unset _JAVA_OPTIONS
      - run: chmod +x ./gradlew
      - run: ./gradlew check --no-daemon
workflows:
  build:
    jobs:
      - build
