version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    environment:
      JAVA_TOOL_OPTIONS: ""  # anula os 64m da imagem
    steps:
      - checkout
      - run:
          name: Dar permissão e rodar
          command: |
            chmod +x ./gradlew
            ./gradlew check
workflows:
  build:
    jobs:
      - buil
